# Defines what linker should be used for installing Node packages (useful to
# enable the node-modules plugin), one of: pnp, pnpm and node-modules.
nodeLinker: node-modules

# The yarnPath setting is currently the preferred way to install Yarn within a
# project, as it ensures that your whole team will use the exact same Yarn
# version, without having to individually keep it up-to-date.
yarnPath: .yarn/releases/yarn-3.2.0.cjs
